# -*- coding: utf-8 -*-
"""My Jupyter Notebook on IBM Watson Studio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKHdoT1BRhtAl-RTlo3Jl5LacO2z7mHm

#My Jupyter Notebook on IBM Watson Studio

**Yosimar Oswaldo Serrano Silva**<br>
Data Scientist

*I am interested in data science because I like to work whith data and Machine Learnign Algorithms. Also, I like to analyze an visualize data to find useful insights*

### The next code get the result of sum 2 numbers and printed it
"""

a= 4+5
print (a)

"""*   Bullet list
*   Bullet list

1.   Numbered List
2.   Numbered list

---
Horizontal Rule

[Hyperlink](https://prueba.com)





"""